analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.703547
  lightness: 0.538592
  rhythmicContrast: 0.015673
  saturation: 0.409861
cta: {}
layout_spectrum: 0.727195
name: Deborah Carr Makeup Artist
opengraph: {}
purpose: {}
typography_spectrum: 0.127533
