name: Deborah Carr Makeup Artist
favicon: null
layout_spectrum: 0.727195
typography_spectrum: 0.127533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.703547
  lightness: 0.538592
  saturation: 0.409861
  rhythmicContrast: 0.015673
purpose:
  - name: null
    item: null
    url: null
